### ISSUE TITLE
Practica 5 Diseño de control Personalizado

### ISSUE THREAD

**Issue by Arnold-Js** [SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Arnold-Js#2]
[Practica 5_Reporte Boton_Personalizado.pdf](https://github.com/SistemasTecTlaxiaco/diseno-de-control-para-cajas-de-texto-Arnold-Js/files/8348983/Practica.5_Reporte.Boton_Personalizado.pdf)

**Comment by IrvingFernand0** [comment]
Esta práctica obtuvo 100% 
Correspondiente a **20** de calificación

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
